import uuid
from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta

class BacktestEngine:
    """
    Backtesting module for validating signal performance against historical data.
    Implements walk-forward validation and accounts for slippage.
    """
    
    def __init__(self, initial_capital: float = 10000.0, slippage_bps: int = 5, maker_fee_bps: int = 10):
        self.initial_capital = initial_capital
        self.slippage = slippage_bps / 10000.0
        self.fee = maker_fee_bps / 10000.0

    def run_backtest(self, 
                    symbol: str, 
                    historical_candles: List[Dict[str, Any]], 
                    signals: List[Dict[str, Any]], 
                    strategy_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Run a simulated backtest on a single asset.
        
        - historical_candles: List of {"timestamp": "...", "close": 123.4}
        - signals: List of historical signals generated by the model
        - strategy_config: E.g., {"take_profit_pct": 0.05, "stop_loss_pct": 0.02}
        """
        if not historical_candles:
            raise ValueError("No historical data provided for backtest")

        capital = self.initial_capital
        position = 0.0 # Asset quantity
        entry_price = 0.0
        
        trades = []
        equity_curve = []
        
        tp_pct = strategy_config.get("take_profit_pct", 0.05)
        sl_pct = strategy_config.get("stop_loss_pct", 0.02)
        
        # Sort data
        candles = sorted(historical_candles, key=lambda x: x["timestamp"])
        
        # Simple map of timestamp to signal for O(1) lookup
        # In reality, timestamps might not align perfectly, so we'd need nearest-neighbor search
        signal_map = {s["timestamp"][:10]: s for s in signals} # Group by date
        
        for candle in candles:
            date_key = candle["timestamp"][:10]
            current_price = candle["close"]
            
            # Record daily equity
            current_equity = capital + (position * current_price)
            equity_curve.append({
                "timestamp": candle["timestamp"],
                "equity": current_equity
            })
            
            # Check Stop Loss / Take Profit if in position
            if position > 0:
                profit_pct = (current_price - entry_price) / entry_price
                if profit_pct >= tp_pct or profit_pct <= -sl_pct:
                    # Close position
                    exit_price = current_price * (1 - self.slippage)
                    revenue = position * exit_price
                    revenue -= (revenue * self.fee)
                    capital += revenue
                    
                    trades.append({
                        "type": "SELL",
                        "timestamp": candle["timestamp"],
                        "price": exit_price,
                        "reason": "TP" if profit_pct >= tp_pct else "SL",
                        "pnl": revenue - (position * entry_price),
                        "pnl_pct": profit_pct
                    })
                    position = 0.0
                    entry_price = 0.0
                    continue
                    
            # Check for new signals
            if date_key in signal_map and position == 0:
                sig = signal_map[date_key]
                if sig.get("direction") in ["bullish", "strong_bullish"]:
                    # Buy
                    entry_price = current_price * (1 + self.slippage)
                    amount_to_invest = capital * 0.95 # Invest 95% of available capital
                    
                    position = (amount_to_invest - (amount_to_invest * self.fee)) / entry_price
                    capital -= amount_to_invest
                    
                    trades.append({
                        "type": "BUY",
                        "timestamp": candle["timestamp"],
                        "price": entry_price,
                        "reason": "SIGNAL",
                        "amount": position
                    })
                    
        # Close out any remaining position at the end
        if position > 0:
            final_price = candles[-1]["close"] * (1 - self.slippage)
            revenue = position * final_price
            revenue -= (revenue * self.fee)
            capital += revenue
            trades.append({
                "type": "SELL",
                "timestamp": candles[-1]["timestamp"],
                "price": final_price,
                "reason": "END_OF_BACKTEST",
                "pnl": revenue - (position * entry_price),
                "pnl_pct": (final_price - entry_price) / entry_price
            })
            
        final_equity = capital
        total_return = (final_equity - self.initial_capital) / self.initial_capital
        
        # Calculate metrics
        winning_trades = [t for t in trades if t.get("type") == "SELL" and t.get("pnl", 0) > 0]
        losing_trades = [t for t in trades if t.get("type") == "SELL" and t.get("pnl", 0) <= 0]
        
        hit_rate = len(winning_trades) / (len(winning_trades) + len(losing_trades)) if trades else 0.0
        
        # Calculate max drawdown
        max_dd = 0.0
        peak = self.initial_capital
        for eq in equity_curve:
            if eq["equity"] > peak:
                peak = eq["equity"]
            dd = (peak - eq["equity"]) / peak
            if dd > max_dd:
                max_dd = dd

        return {
            "id": str(uuid.uuid4()),
            "symbol": symbol,
            "metrics": {
                "initial_capital": self.initial_capital,
                "final_equity": final_equity,
                "total_return_pct": total_return * 100,
                "hit_rate_pct": hit_rate * 100,
                "max_drawdown_pct": max_dd * 100,
                "total_trades": len([t for t in trades if t["type"] == "SELL"])
            },
            "trades": trades,
            "equity_curve": equity_curve
        }

backtest_engine = BacktestEngine()
